version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase # Connection string for MongoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Map MongoDB default port
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data:
